### ISSUE TITLE
undefined method pay_key

### ISSUE THREAD

**Issue by riaw** [flippa/pp-adaptive#8]
Not sure if it's a coding mistake on my part or a bug, but I'm getting error, undefined method pay_key when i try to redirect to paypal, Link is:

<%= link_to "confirm donation", 'https://www.sandbox.paypal.com/webscr?cmd=_ap-payment&paykey='"#{response.pay_key}" %>

**Comment by moussasarr** [comment]
Does this gem support IPN notifications ? How did you guys handle the IPN notifications ?
